steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'europe-west4-docker.pkg.dev/wally-registry-449109/wally-backend/wally-backend:$COMMIT_SHA',
      '-f',
      'wally-registry-backend/Dockerfile',
      '.'
    ]

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west4-docker.pkg.dev/wally-registry-449109/wally-backend/wally-backend:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "wally-backend",
        "--image",
        "europe-west4-docker.pkg.dev/wally-registry-449109/wally-backend/wally-backend:$COMMIT_SHA",
        "--region",
        "europe-west4",
        "--platform",
        "managed",
        "--command",
        "./launch",
        "--allow-unauthenticated",
      ]

timeout: 900s
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
serviceAccount: "wally-service-account@wally-registry-449109.iam.gserviceaccount.com"
